---
date: "2021-06-03T09:00:00-00:00"
title: "Innovations in Applied Data Symposium"
subtitle: "Nau te Rourou, Naku re Rourou"
description: "An opportunity for you to share the cool stuff being done with data in Aotearoa New Zealand. "
location: "Te Papa in Wellington and Online"
cost: "Free to attend"
registration: "Required, details to follow"
event_url: ""
funding:
- SWA
- Healthier Lives
- iNZight Analytics
url: "/symposium"
---

Want to hear about the fantastic data innovations being developed in Aotearoa New Zealand?

This one-day symposium is an opportunity to hear about current and recent work involving applied data and network with those working in the area. The programme involves lots of brief (5 mins max) presentations, keynote speakers as well as opportunities for networking. Talks will be grouped into themes on similar topics and/or data types, with plenty of time for catching up with colleagues in between sessions.

Registration is required, but there is no charge. Lunch as well as morning and afternoon teas will be provided as part of the registration. There will even be a coffee cart dispensing decent coffee.

Expect to hear about cutting edge work including large scale data analytics, data governance and sovereignty, lessons from the COVID pandemic, new analytics tools, including freeware as well as lots of other novel data stuff presented by people doing the work.

The symposium is open to anybody working in the collection, management, analysis or access to applied data, from government, non-government and academic environments.
