baseURL = ""
languageCode = "en-us"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
theme = "hugo-initio"
publishDir = "public"

buildFuture = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    name = "Te Rourou Tātaritanga"
    email = "terourou@vuw.ac.nz"
    phone = ""
    address = "Wellington, New Zealand"
    year = 2021
    # avatar = "images/guy.jpg"
    avatarclass = "circle"
    background = ""
    # banner = "images/bg_head.jpg"
    # favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

# [[menu.main]]
#     name = "home"
#     url = "/"
#     weight = 1
[[menu.main]]
    name = "events"
    url = "/events/"
    weight = 10
[[menu.main]]
    name = "posts"
    url = "/post/"
    weight = 30

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

# [[params.social]]
# 	title = "facebook"
# 	url = "https://www.facebook.com/nickname"
#     icon = "fab fa-facebook-square"
#     footer = true
#     sharethis = true
#     network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/terourou"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
# [[params.social]]
# 	title = "instagram"
# 	url = "https://www.instagram.com/nickname"
#     icon = "fab fa-instagram"
#     footer = true
#     sharethis = false
#     network = ""
# [[params.social]]
# 	title = "google+"
# 	url = "https://plus.google.com/+nickname"
#     icon = "fab fa-google-plus-square"
#     footer = false
#     sharethis = true
#     network = "googleplus"
# [[params.social]]
# 	title = "linkedin"
# 	url = "https://www.linkedin.com/in/nickname"
#     icon = "fab fa-linkedin"
#     footer = false
#     sharethis = true
#     network = "linkedin"
# [[params.social]]
# 	title = "tumblr"
# 	url = "https://nickname.tumblr.com"
#     icon = "fab fa-tumblr-square"
#     footer = false
#     sharethis = false
#     network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/terourou"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:terourou@vuw.ac.nz"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
