baseURL = "https://terourou.github.io/"
languageCode = "en-us"
title = "Te Rourou Tātaritanga"
theme = "hugo-initio"
publishDir = "public"

buildFuture = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    name = "Te Rourou Tātaritanga"
    # email = "team@terourou.nz"
    # phone = ""
    address = "Victoria University of Wellington\nWellington, New Zealand"
    year = 2021
    avatar = "img/logo.png"
    avatarclass = "circle"
    background = ""
    banner = "img/wgtn.jpg"
    banner_attr = "Tony Wills"
    banner_attr_details = "CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons"
    banner_attr_url = "https://commons.wikimedia.org/wiki/File:Wellington_Harbour_01.jpg"
    # favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "events"
    url = "/events/"
    weight = 10
# [[menu.main]]
#     name = "posts"
#     url = "/post/"
#     weight = 30
[[menu.main]]
    name = "team"
    url = "/team/"
    weight = 40

[[menu.main]]
    name = "related"
    url = "/"
    weight = 50
    identifier = "related"

#### ---------------------------------- Related Links
[[menu.main]]
    parent = "related"
    name = "iNZight"
    url = "https://inzight.nz"

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

# [[params.social]]
# 	title = "facebook"
# 	url = "https://www.facebook.com/nickname"
#     icon = "fab fa-facebook-square"
#     footer = true
#     sharethis = true
#     network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/terourou"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
# [[params.social]]
# 	title = "instagram"
# 	url = "https://www.instagram.com/nickname"
#     icon = "fab fa-instagram"
#     footer = true
#     sharethis = false
#     network = ""
# [[params.social]]
# 	title = "google+"
# 	url = "https://plus.google.com/+nickname"
#     icon = "fab fa-google-plus-square"
#     footer = false
#     sharethis = true
#     network = "googleplus"
# [[params.social]]
# 	title = "linkedin"
# 	url = "https://www.linkedin.com/in/nickname"
#     icon = "fab fa-linkedin"
#     footer = false
#     sharethis = true
#     network = "linkedin"
# [[params.social]]
# 	title = "tumblr"
# 	url = "https://nickname.tumblr.com"
#     icon = "fab fa-tumblr-square"
#     footer = false
#     sharethis = false
#     network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/terourou"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:team@terourou.nz"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"

#[[params.affiliates]]
#    title = "Victoria University of Wellington"
#    url = "https://wgtn.ac.nz"
#    logo = "/img/uvic.png"

#[[params.affiliates]]
#    title = "University of Auckland"
#    url = "https://auckland.ac.nz"
#    logo = "/img/uoa.png"
